create table Crimes (
	ID BIGINT PRIMARY KEY,
    CaseNumber VARCHAR(100),
    Date DATETIME,
    Block VARCHAR(100),
    IUCR VARCHAR(100),
    PrimaryType VARCHAR(100),
    Description VARCHAR(100),
    LocationDescription VARCHAR(100),
    Arrest BIT,
    Domestic BIT,
    Beat VARCHAR(100),
    District VARCHAR(100),
    Ward VARCHAR(100),
    CommunityArea VARCHAR(100),
    FBICode VARCHAR(100),
    XCoordinate DOUBLE NULL,
    YCoordinate DOUBLE NULL,
    Year INT,
    UpdatedOn DATETIME,
    Latitude DOUBLE NULL,
    Longitude DOUBLE NULL,
    Location VARCHAR(100) NULL
)